VIRTUAL_WIDTH = 384
VIRTUAL_HEIGHT = 216

WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

CTRL_UP = 'up'
CTRL_DOWN = 'down'
CTRL_LEFT = 'left'
CTRL_RIGHT = 'right'
CTRL_OK = 'z'
CTRL_BACK = 'x'
CTRL_HEAL = 'c'
CTRL_START = 'enter'

TILE_SIZE = 16